name: Generate PDF from README

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Convert README.md to PDF
        run: |
          pandoc README.md -o README.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-pdf
          path: README.pdf
